#ifndef FONTERROR_H
#define FONTERROR_H

enum fe_errors {
    FE_OK = 0x0,
    FE_CANT_FIND_FILE = 0x2,
    FE_INVALID_FILE = 0x3,
    FE_CORRUPT_FILE = 0x4,
    FE_FONT_NOT_FOUND = 0x5,
    FE_FONT_NOT_LOADED = 0x6,
    FE_FONT_ALREADY_LOADED = 0x7,
    FE_INVALID_FONT_TYPE = 0x8,
    FE_INVALID_PARAMETER = 0x9,
    FE_GLYPH_ERROR = 0x10,
    FE_GLYPH_NOT_CACHED = 0x11,
    FE_STROKER_ERROR = 0x12,
    FE_NOT_ENOUGH_MEMORY = 0x13,
    FE_INVALID_ATLAS_ID = 0x14,
    FE_ATLAS_IS_FULL = 0x15,
    FE_UNKNOWN_ERROR = 0x99
};

#endif // FONTERROR_H
